### ISSUE TITLE
能不能具体点啊，表示不知道怎么用？

### ISSUE THREAD

**Issue by lb-never** [StruggleBird/asset-cache-control#1]
1、能不能具体点啊，表示不知道怎么用？

**Comment by StruggleBird** [comment]
按照示例，在你的web工程pom文件里面贴上这段代码：
`<build>
    <plugins>
        <plugin>
            <groupId>org.zt</groupId>
            <artifactId>asset-cache-control</artifactId>
            <version>1.0.0</version>
            <executions>
                <execution>
                    <id>version</id>
                    <phase>prepare-package</phase>
                    <goals>
                        <goal>version</goal>
                    </goals>
                </execution>
            </executions>
        </plugin>
    </plugins>
</build>`

然后在工程根目录执行 mvn package命令 ，看看效果再说，应该能了解个大概吧 。

**Comment by StruggleBird** [comment]
用package命令打出来的包 ，会自动把webapps目录下面的动态文件（jsp文件）里面的每个链接添加上版本信息 ，就这样 。

记得每次在执行package命令之前， 要执行一次 svn revert 命令，确保你的源码不会重复打版本号。
