### ISSUE TITLE
class not found 

### ISSUE THREAD

**Issue by jicu7766240** [StruggleBird/asset-cache-control#3]
你好：
我是直接把jar下载放到nexus里面的。
然后在pom里面放入示例代码。
执行 mvn asset-cache-control:package 报错。

错误信息如下：
[ERROR] Failed to execute goal org.zt:asset-cache-control:1.0.1:package (default
-cli) on project XXX: Execution default-cli of goal org.zt:asset-cach
e-control:1.0.1:package failed: A required class was missing while executing org
.zt:asset-cache-control:1.0.1:package: org/apache/commons/lang/StringUtils
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.zt:asset-cache-control:1.0.1
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/C:/Users/xiaoxi/.m2/repository/org/zt/asset-cache-contro
l/1.0.1/asset-cache-control-1.0.1.jar
[ERROR] urls[1] = file:/C:/Users/xiaoxi/.m2/repository/org/codehaus/plexus/plexu
s-utils/1.1/plexus-utils-1.1.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[project>bxtx.intf.insure:yon
gcheng_intf:1.0.0, parent: ClassRealm[maven.api, parent: null]]]
[ERROR]
[ERROR] -----------------------------------------------------: org.apache.common
s.lang.StringUtils
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContaine
rException

请问这个要怎么解决？

**Comment by StruggleBird** [comment]
这个插件会依赖一些jar包 ，按理说 如果你的nexus配置正确的话，会自动下载依赖jar包的 ，目前依赖这些jar
`<dependency>
            <groupId>org.apache.maven</groupId>
            <artifactId>maven-plugin-api</artifactId>
            <version>3.0.5</version>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.11</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>log4j</groupId>
            <artifactId>log4j</artifactId>
            <version>1.2.17</version>
        </dependency>
        <dependency>
            <groupId>commons-lang</groupId>
            <artifactId>commons-lang</artifactId>
            <version>2.6</version>
        </dependency>
        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
            <version>2.4</version>
        </dependency>
        <dependency>
            <groupId>org.apache.maven</groupId>
            <artifactId>maven-project</artifactId>
            <version>2.2.0</version>
            <optional>true</optional>
        </dependency>`
根据你的错误信息看，是commons-lang包没有在本地找到 ，可以尝试手动下载一个commons-lang：2.6版本的包，然后放到本地maven仓库中试试 ，同理出现其他的缺少jar的情况也是这样处理。

**Comment by jelly-mazic** [comment]
我也遇到了相同的问题, 也按照上面解释在pom.xml中添加commons-lang, 本地仓库中也有对应的jar. 但是执行mvn asset-cache-control:version 命令还是报出相同的错误.
错误如下: 
[ERROR] Failed to execute goal org.zt:asset-cache-control:1.0.2:version (default-cli) on project js: Execution default-cli of goal org.zt:asset-cache-control:1.0.2:version failed: A required class was missing while executing org.zt:asset-cache-control:1.0.2:version: org/apache/commons/lang/StringUtils
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.zt:asset-cache-control:1.0.2
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/D:/Repository/mavenRepository/org/zt/asset-cache-control/1.0.2/asset-cache-control-1.0.2.jar
[ERROR] urls[1] = file:/D:/Repository/mavenRepository/org/codehaus/plexus/plexus-utils/1.1/plexus-utils-1.1.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR] 
[ERROR] -----------------------------------------------------
[ERROR] : org.apache.commons.lang.StringUtils
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException

**Comment by StruggleBird** [comment]
如果编译环境不好配置，可以直接在这里下载jar包和源码包：
https://github.com/StruggleBird/asset-cache-control/releases
