### ISSUE TITLE
Maven 中央仓库无法找到

### ISSUE THREAD

**Issue by jelly-mazic** [StruggleBird/asset-cache-control#4]
请问大神, 该插件是不是在Maven的中央仓中失效了.
我在https://mvnrepository.com/search?q=asset-cache-control,中搜索找不到asset-cache-control插件
在阿里云的镜像仓库中也找不到(http://maven.aliyun.com/mvn/search)

**Comment by StruggleBird** [comment]
目前并没有上传到中央仓库，需要自行下载源码编译打包，并存放于私服 。

**Comment by jelly-mazic** [comment]
谢谢\^0^/
